version: "3.1"
services:
    db:
        container_name: mysql_db_container
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - ./.env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
        volumes:
            # import sql database
            - ./src/sql/shop_db.sql:/docker-entrypoint-initdb.d/shop_db.sql
        networks:
            - default
    www:
        build: .
        ports: 
            - "3000:80"
        volumes:
            - ./src:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: php_container
        links: 
            - db:db
        ports:
            - 8000:80
        env_file:
            - ./.env
        environment:
            MYSQL_USER: ${MYSQL_ROOT_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
volumes:
    persistent: